# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "Ngoma The Brand / %s"
og_image: /img/og_ngoma.png
author: Simon Ngoma
favicon: /img/favicon.png
description: Digital Media Consultant
port: 8083

# OG image
origin: https://ngomathebrand.cc/
og: /img/og_ngoma.png
theme-color: "#000000"


navigation:
  header:
    - About: /about/
    - Services: /all-services/
    - Projects: /all-projects/
    - Contact: /contact/
  logo: /img/avatar.jpg
  menu: /img/burger-menu.svg

  footer:
    contact:
    - image: /img/x-social-media.svg
      url: //x.com/cymone_rayan
      alt: Twitter (X) profile
      size: 22 x 22
    - image: /img/linkedin.svg
      url: //linkedin.com/in/ngoma-simon-1b0ab2114
      alt: LinkedIn profile
      size: 26 x 26
    - image: /img/call.svg
      url: //calendly.com/ngomasimon3/60min
      alt: Schedule a call
      size: 26 x 26
    - image: /img/gmail.svg
      url: mailto:ngomasimon3@gmail.com
      alt: Gmail
      size: 26 x 26
    - image: /img/tiktok.svg
      url: //tiktok.com/@simonngoma
      alt: Tiktok
      size: 26 x 26
    - image: /img/Facebook.svg
      url: //tiktok.com/@simonngoma
      alt: Facebook
      size: 26 x 26